version: '3'
tasks:
  build:
    silent: true
    aliases: [b]
    desc: build ttedit for current platform
    cmds:
      - go build -v -o ./bin/ttedit ./main.go

  run:
    silent: true
    aliases: [r]
    deps: [build]
    desc: run ttedit
    cmds:
      - ./bin/ttedit

  clean:
    silent: true
    desc: clean project
    cmds:
      - rm -rf ./bin
      - go clean
